[workspace]
resolver = "2"

default-members = [
    "conjure_oxide",
    "crates/conjure_core",
    "solvers/sat",
    "solvers/minion",
]

members = [
    "conjure_oxide",
    "crates/conjure_core",
    "crates/enum_compatability_macro",
    "crates/conjure_macros",
    "solvers/minion",
    "crates/tree-sitter-essence",
    "crates/tree_morph", 
    "solvers/sat",
]

[workspace.lints.clippy]
unwrap_used = "warn"
expect_used = "warn"
wildcard_imports = "warn"

[profile.dev]
codegen-units = 1

[profile.release]
codegen-units = 1
